### PR TITLE
Add illustration for Akka Cluster Client/Akka HTTP impl.

### PR DESCRIPTION
**Pull request by eloots**

### CODE REVIEW

**Comment by hughesj** [comment]
hi Eric, are all the actors instantiated on all the cluster nodes? I was wondering about the actor creation process and whether there's just 9 each of row/column/block and they're spread out / sharded across the nodes?

**Comment by eloots** [comment]
Hi Jeremy, good question actually!

There exactly one solver running on each node. So 1+3*9 * 1 = 29 actors/node. I hope that the illustration (images/sudukoSolverClusterClientAkkaHTTP.png) makes that clear.

One could (theoretically) imagine spreading the actors of a single solver across multiple nodes, but that would be complex as one would have to take into account message delivery guarantees: messages may get lost, so you'd have to account for that in your code. It's not worth the effort because:
- it adds a lot of complexity (message delivery guarantees)
- sending the messages over a network is orders of magnitude slower than the delivery of messages between actors running inside an actor system (as these are passed in-memory)

We may end up implementing a sharded version of the solver: this version can cache solutions to previously solved problems (as suggested by @henrikengstrom)

Note that the Soduku solver is compute-bound - rather atypical for an Akka based service implementation. Solving a puzzle takes ± 1 second on a Raspberry Pi 3 node (compared to ± 10 milliseconds on my MacBook Pro) 😉

**Comment by hughesj** [comment]
Hi Eric, thanks. It makes me wonder if there's a description of the pros/cons of spreading actors over a network. I though, a design goals for Akka is for actors to communicate using value semantics so the programming model doesn't change when actors are remote from each other. But, it sounds like 'message delivery guarantees' need to be considered when they are remote. Certainly a good use-case and demo of a sharded application would be interesting. Thanks.

**Comment by henrikengstrom** [comment]
@hughesj Eric and I discussed whether or not to add cluster sharding to the tutorial. At the end of the day there is only so much information one can feed to the participants. Right now I believe that there is 5h set aside, at Scala Days, to get through all the exercises in this repo. That's already borderline too much if you ask me. That said, we can always add exercises to this repo and decide where the cutoff time is for different tutorials/audiences a.s.o.   

Also, adding new exercises is quite time consuming so we're also bound by that :)

Wrt your questions about local vs remote, it is true that Akka is designed so that the location of an actor is transparent. That does not mean that one should spread actors out over nodes just because it is possible. On the contrary, remote calls should be restricted if possible as a remote call always introduces uncertainties in terms of delivery, time, etc. Akka Cluster uses the location transparency under the hood to implement its feature set which, without location transparency, would be very difficult to achieve. Eric and I decided that this could be a good discussion topic at the end of the tutorial if there is any time for it.

**Comment by eloots** [comment]
@hughes To add to what @henrikengstrom already said: the _problem_ is that reliable message delivery between nodes in a cluster is an example of the problem of reliable message delivery in a distributed system in general.

In a distributed system, one can prove mathematically that _exactly once_ message delivery is impossible. In practice though, appropriate techniques can bring us 'pretty close' to achieving _exactly once_ message delivery. It's not simple to achieve this and many aspects come into play:
- _At least once_ delivery
- Persistence (because one or both actors may crash during a conversation, potentially leading to losing one or more messages)
- The ordering of messages (if ordering is important to the application)
- Idempotency when processing duplicated messages

In fact, this is part of [a course](https://www.lightbend.com/services/training/lightbend-reactive-architecture-professional) we organize at LB. 😉

**Pull request merged**
