### PR TITLE
Gather file to folders plus fix paths in docs/scripts

### PR DESCRIPTION
**Pull request by agolubev**
now root folders are:
- docs
- led
- scripts

going to add `display` folder and perhaps some differentiations in scripts

### CODE REVIEW

**Comment by agolubev** [comment]
@eloots

> Moving the documentation to a subfolder is a good idea.

Ok, is moving scripts to subfolder a good idea?
Perhaps root subfolder structure could be similar LSL-P so all exercises will be in a separate subfolder. What do you think?

>By the way: this move has broken the project: try loading it in SBT and had merge conflicts at the time you submitted it

PR was mainly to illustrate ideas as long as this is my first commit.  (of course, it can be rebased at the end). I talked with Kiki so far about this.

> Once "display" exercises are added to the repo, it would be a good idea to make users aware of the type of exercise they are running

I will certainly add docs to display portion but don't know how effectively separate led with display. The best idea so far just has different folders with separate sbt projects (folder structure is similar to  LSL-P) and this what is in PR. I'm thinking that having led and display exercises in the same folder is possible in case the display will go after led as it requires some reinstallation. Anyway there will be two logical groups. But you are right that code for led will not crush for display and vice versa

Additional Questions:
- I noticed that nextExcercise/prevExercise does not work - are there plans to add this in the future?
- Also, did you think about having deploying/running functionality at sbt plugin instead of scripts?

**Comment by eloots** [comment]
> Ok, is moving scripts to subfolder a good idea?
Perhaps root subfolder structure could be similar LSL-P so all exercises will be in a separate subfolder. What do you think?

There are currently 2 types of scripts: the first are scripts that are executed on the user's laptop; it is awkward to move these to a subfolder as a user would have to type `scripts/copy`. Examples are `copy`, `clrJars`, `updateScripts`, ... The second type of scripts are `run` and `runDocker`: it would be good to move these to a subfolder as it would be much cleaner and confusing to the user.

As for moving things to a subfolder: That's possible, but I think that that doesn't add much value in this set-up. Changing it now would probably create confusion for those who have been using the present configuration.

> I noticed that nextExcercise/prevExercise does not work - are there plans to add this in the future?

That works on condition that this repository is run through `studentify` (part of the [course management tools](https://github.com/lightbend/course-management-tools)).

> Also, did you think about having deploying/running functionality at sbt plugin instead of scripts?

I've been thinking about this indeed. That would be a nice feature to implement.

**Comment by eloots** [comment]
@agolubev Alex: I think this PR can be closed as it has been superseded by #118 and #130 . Can you take care if that?

**Comment by agolubev** [comment]
@eloots  sure. Closing it.

**Pull request closed without merging**
